services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: djangowalletoperations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    # volumes:
    #   - db-volume:/var/lib/postgresql/data
    networks:
      - wallets-net

  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      POSTGRES_DB: djangowalletoperations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST: db
    networks:
      - wallets-net

# volumes:
#   db-volume:
#     driver: local

networks:
  wallets-net: